### ISSUE TITLE
Can you add an iOS Demo ?

### ISSUE THREAD

**Issue by PatrickSCLin** [sbennett912/SwiftGL#2]
Hi, is possible to add an iOS Demo target in this project ?

I tried to use your framework to create a simple iOS project,

but always got "EXC_BAD_ACCESS" when glDrawElements called

**Comment by PatrickSCLin** [comment]
problem solved, I should new VAO, VBO after setup EaglContext

**Comment by nullcatalyst** [comment]
I'm glad you figured it out. But as per your suggestion, I created a demo application anyway, so that it might help anyone else trying to use the project.
